Checking for conda errors

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -44,9 +44,16 @@ jobs:
           benchit benchmark models/selftest/linear.py --build-only --use-slurm --cache-dir local_cache
 
           # Check results
-          cat slurm-1.out
-          if ! grep -q "Model successfully built!" slurm-1.out
+          SLURM_OUTPUT="slurm-1.out"
+          if ! grep -q "Model successfully built!" $SLURM_OUTPUT
           then
+              cat $SLURM_OUTPUT
               echo "Model has not been successfully built"
+              exit 1
+          fi
+          if ! grep -q "CommandNotFoundError" $SLURM_OUTPUT
+          then
+              cat $SLURM_OUTPUT
+              echo "CommandNotFoundError fount in slurm output. This is likely due to conda not being found."
               exit 1
           fi
